// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxsHllzQkm0muJbIDvXqfev-WV5_PiYFM',
    appId: '1:210402467847:web:3f60669e115c96e0d58aa2',
    messagingSenderId: '210402467847',
    projectId: 'rifas-ieaderp',
    authDomain: 'rifas-ieaderp.firebaseapp.com',
    storageBucket: 'rifas-ieaderp.appspot.com',
    measurementId: 'G-206NHFEMW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEzMM9CG7KK4KS06Gl1IhP7ud6SaOcjUE',
    appId: '1:210402467847:android:685ae7c560ff6581d58aa2',
    messagingSenderId: '210402467847',
    projectId: 'rifas-ieaderp',
    storageBucket: 'rifas-ieaderp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj50vkyWxUjAnI2jE9Q5PBv8lmH5kw38E',
    appId: '1:210402467847:ios:7030e51da826d0bdd58aa2',
    messagingSenderId: '210402467847',
    projectId: 'rifas-ieaderp',
    storageBucket: 'rifas-ieaderp.appspot.com',
    iosClientId: '210402467847-cudsqivb4qkpgkoce59hs6jssqvd41c0.apps.googleusercontent.com',
    iosBundleId: 'com.example.rifas',
  );
}
